name: Test Cankaya

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test with curl
        run: |
          curl -v \
          --resolve basvuru.cankaya.bel.tr:443:212.175.136.176 \
          --http1.1 \
          https://basvuru.cankaya.bel.tr/
